apiVersion: v1
kind: Service
metadata:
  name: fiap-soat-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: fiap-soat
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
  type: LoadBalancer
